### ISSUE TITLE
What is the use of this module

### ISSUE THREAD

**Issue by rfyiamcool** [thombashi/DateTimeRange#3]
What is the use of this module?

**Comment by thombashi** [comment]
This module to simplify the routine work processing of a time range, such as checks whether a certain time is within the time range, get the overlap of the time range to each other or truncate certain time.

I sometimes want to handle the range of a particular time. For example, the execution time of a process/query (time from the start to the end), extract information for a specific time zone, etc.. This module was created in order to reduce the time and effort of these cases.

**Comment by thombashi** [comment]
I'm going to close this issue, as I update the README which I believe answer to you question. Anyway thanks for the issue.
